### ISSUE TITLE
db.get Legacy range options ("start" and "end") have been removed

### ISSUE THREAD

**Issue by scenaristeur** [scenaristeur/os#1]
```
node::local> get()
Uncaught Error: Legacy range options ("start" and "end") have been removed
    at cleanRangeOptions (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/abstract-leveldown/abstract-leveldown.js:306:13)
    at DB.AbstractLevelDOWN._setupIteratorOptions (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/abstract-leveldown/abstract-leveldown.js:287:13)
    at DB.AbstractLevelDOWN.iterator (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/abstract-leveldown/abstract-leveldown.js:329:18)
    at LevelUP.readStream.LevelUP.createReadStream (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/levelup/lib/levelup.js:301:37)
    at LevelUP.valueStream.LevelUP.createValueStream (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/levelup/lib/levelup.js:311:15)
    at Object.getStream (/home/smag/dev/os/core/levelgraph-jsonld/node_modules/levelgraph/lib/levelgraph.js:59:28)
node::local> 

```

must update "abstract leveldown" https://github.com/Level/abstract-leveldown/blob/master/UPGRADING.md#700

**Comment by scenaristeur** [comment]
upgrade levelgraph dependencie 2.0.0 > 3.0.0 in levelgraph-jsonjs

Package     Current  Wanted  Latest  Location                 Depended by
levelgraph    2.1.1   2.1.1   3.0.0  node_modules/levelgraph  levelgraph-jsonld
